on:
  workflow_dispatch:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - uses: excitedleigh/setup-nox@v2.0.0
  - run: nox -r
